#--------------------------------------------------------
# Hexo-MengD(萌典)
# 项目地址：https://github.com/lete114/hexo-theme-MengD
# 主题文档：https://mengd.js.org
# 一个简洁、轻量的Hexo主题
#--------------------------------------------------------

# 关于如何提高访问速度：https://github.com/lete114/hexo-minify

# 导航栏菜单
menu:
  enable: true # 是否开启导航栏
  # 首页: /
  # 找文章:
  #   - 标签 || /tags
  #   - 分类 || /categories
  #   - 归档 || /archives
  # 友情链接: /link
  # 关于我: /about

# 图标
social:
  # fab fa-github: https://github.com/lete114
  # fa fa-envelope: mailto:lete@lete114.top

title: # 网站标题支持html，可写img标签等
favicon: /img/favicon.png
avatar: /img/logo.gif
pageCount: 5 # 首页展示文章数
darkmode: true # 深色模式
pjax: true # pjax
search: false # 需安装插件: npm install hexo-generator-search --save

# 置顶文章
stick:
  # 例如: text: <i class="fas fa-arrow-up"></i>置顶
  text: # 支持html
  color: '#ffa51e' # 置顶标签文字颜色

# 自动注册页面
pages:
  tags: true
  categories: true
  error: ## 404页面
    enable: true
    text: 404 Not Found

# 目录
toc:
  enable: true
  options: # 详细配置: https://hexo.io/zh-cn/docs/helpers#toc
    list_number: false

## 主题颜色
themeColor:
  main: '#e58a8a' # 主色
  bodyA: '#00c4b6' # 全局a标签颜色
  title: '#ff7242' # 博主昵称

open_graph:
  enable: true
  options: # 详细配置: https://hexo.io/zh-cn/docs/helpers#open-graph

# 有趣的标题切换
amusingTitle:
  enable: true
  leaveTitle: '(つェ⊂) 我藏好了哦~ '
  returnTitle: '(*´∇｀*) 被你发现啦~ '

# 自动截取
description:
  line: 3 # 显示多少行后出现省略号(...)
  length: 150 # 截取多少字

prefetch:
  enable: true # 是否启用预加载
  load: true # 是否在页面所有资源加载完毕后再进行预加载
  delay: 1000 # 延迟1秒后预加载
  threshold: 25 # 目标元素在浏览器可视区域25%时触发预加载
  # 自定义预加载资源，如果你开启了本地搜索功能，可以将下方的注释去掉，当使用搜索时不用等太长的请求时间
  # customs: [/seatch.json]

# 将文章页的所有外链转换为卡片式外链
cardlink: true

# 图片懒加载
lazyload:
  enable: true
  loadimg: /img/load.gif

# 代码块高亮主题
highlightTheme: mac # default / darker / pale night / light / ocean / mac / mac light
codeBlockExpand: # 是否开启代码块折叠
  enable: true
  height: 400 # 代码块高度超过400折叠 单位px
  scrollTop: 200 # 展开后,再次(手动点击)点击折叠滚动到代码块开始的距离 单位px

# 自定义引入外部css、js
import:
  headBefore: # 引入到<head>之后
  headAfter: # 引入到</head>之前
  bodyBefore: # 引入到<body>之后
  bodyAfter: # 引入到</body>之前
  # 例如：
  # - <link rel="stylesheet" href="/css/index.css">
  # - '<style>body{color: red}</style>' ## 注意由于css的‘{}’是关键符号所以需要(单/双)引号''
  # - <script>alert(1)</script>

# 文章版权
copyright:
  enable: true
  author: MengD(萌典)
  mail: me@imlete.cn
  licenses: CC BY-NC-SA 4.0||https://creativecommons.org/licenses/by-nc-sa/4.0/ ## 其中||为分隔符，左侧为描述，右侧为版权许可
  description: 本博客所有文章除特别声明外，均采用||许可协议。转载请注明来自
  title: Hexo-Theme-MengD(萌典)

# 页脚
footer:
  since: 2020
  customText: 我相信我可以，但我一直在路上，所以我有无限的可能！！

# 统计(分析)
analytics:
  baidu:
  google:

# 设置字体
font:
  # 全局字体
  html: consolas,Menlo,'PingFang SC','Microsoft YaHei',sans-serif
  # 代码块字体
  code: consolas,Menlo,'PingFang SC','Microsoft YaHei',sans-serif

# 评论
## 注意大小写
comments: discuss # twikoo / waline / valine

# Discuss
## https://discuss.js.org
# 自定义添加 https://discuss.js.org/Quick-Start.html#%E5%AE%A2%E6%88%B7%E7%AB%AF-client
discuss:
  source: https://unpkg.com/discuss@latest/dist/discuss.js
  serverURLs: ## 你的 Discuss 评论系统服务端地址

# valine
## https://valine.js.org/
# 自定义添加 https://valine.js.org/configuration.html
valine:
  source: https://unpkg.com/valine/dist/Valine.min.js
  appid: # 你的 leancloud app id
  appkey: # 你的 leancloud app key

# waline
## https://waline.js.org
# 自定义添加 https://waline.js.org/client/basic.html
waline:
  source: https://unpkg.com/@waline/client/dist/waline.js
  source_css: https://unpkg.com/@waline/client/dist/waline.css
  serverURL: https://env-jxscvzag.service.tcloudbase.com/discuss/mengd # 服务端地址

# twikoo
## https://twikoo.js.org/
twikoo:
  source: https://unpkg.com/twikoo/dist/twikoo.all.min.js
  envId: # 你的环境id

## 说说

# Artitalk
## https://artitalk.js.org/settings.html
artitalk:
  enable: false # 是否开启
  source: https://unpkg.com/artitalk
  title: Artitalk # 标题
  path: artitalk/index.html # 路径
  appid: WhOxxxxxxxxxxxxxMMI #  LeanCloud appId
  appkey: M9Pxxxxxxxxxxxxxxx3Kvs # LeanCloud appKey
  option:

# 主题的css与js引入
## 无特殊要求请勿更改
CDN:
  mainJs: /js/main.js
  mainCss: /css/main.css
  utlis: /js/utlis.js
  search: /js/search.js
  # lazyload
  lazyload: /js/lazyload.js
  # prefetch
  prefetch: /third-party/js/prefetch-page.js
  # cardlink
  cardlink: /third-party/js/cardlink.js
  # pjax
  pjax: /third-party/js/pjax.js
  # fancybox
  fancyboxJs: /third-party/js/fancybox.js
  fancyboxCss: /third-party/css/fancybox.css
  # fortawesome
  fortawesome: /third-party/fontawesome-free/css/all.min.css
